### ISSUE TITLE
Full trust level

### ISSUE THREAD

**Issue by smarteez** [nCubed/TheMovieDbWrapper#10]
When I run call your methods to get data it works fine locally . but when I host it  doesnt work ..... my services provider say it due to Full trust level its there a way it can be Medium trust level?

**Comment by nCubed** [comment]
I suspect the Full trust may be required for the use of System.Reflection in the [MovieDbFactory](https://github.com/nCubed/TheMovieDbWrapper/blob/master/DM.MovieApi/MovieDbFactory.cs). This will take me a day or two to investigate.

In the meantime, could you review this blog post and see if adding any of the web.config settings described here will work? 
https://weblog.west-wind.com/posts/2006/Jul/10/Running-ASPNET-in-Medium-Trust

**Comment by smarteez** [comment]
Hi There 

I have try changing the web.config file as per the blog with no luck ..... would it be possible to create a version with medium trust level . It would be highly  appreciated

**Comment by nCubed** [comment]
I've been doing some testing and additional research and have found that Microsoft no longer supports running in Medium Trust. For example, I cannot even create a new MVC project in Visual Studio 2015 and run the default site in Medium Trust.

Here is a StackOverflow post from someone who works at Microsoft and was previously a security engineer with the the asp.net team: [Is trying to develop for Medium Trust a lost cause?](http://stackoverflow.com/a/17218344) 

Please verify your IIS application pool is running under .NET v4. Something else to verify if the web.config trust level which could explicitly set the trust level to full:

```xml
<configuration>
    <system.web>
        <trust level="Full" />
    </system.web>
</configuration>
```

I wish I had better news. I'll leave the issue open for awhile in case someone else has a solution. For now, I am following the Microsoft guidance of not supporting Medium Trust.
