### ISSUE TITLE
JsonReaderException

### ISSUE THREAD

**Issue by hrafnl** [nCubed/TheMovieDbWrapper#12]
When using IApiPeopleRequest.FindByIdAsync() (retrieving cast members for top rated movies), I get the following unhandled exception:

Newtonsoft.Json.JsonReaderException: Could not convert string to DateTime: 1994. Path 'birtday', line 1, position 226.

Wouldn't it be appropriate for your Json serialization code to include an error delegate for handling DateTime parsing errors like this one?

**Comment by nCubed** [comment]
With the data from TheMovieDb being crowdsourced, sometimes the values can be unexpected; we've been handling these types of errors on a case-by-case basis right now.

Could you provide me the API call? Or the Id passed to `IApiPeopleRequest.FindByIdAsync()`?

**Comment by nCubed** [comment]
Here's an example that will cause the error: `http://api.themoviedb.org/3/person/202080?api_key=<key>`

JSON Result:

```json
{
  "adult": false,
  "also_known_as": [],
  "biography": null,
  "birthday": "1970", <---culprit
  "deathday": "",
  "gender": 2,
  "homepage": "",
  "id": 202080,
  "imdb_id": "nm0173257",
  "name": "Sydney 'Big Dawg' Colston",
  "place_of_birth": "Gary, Indiana, USA",
  "popularity": 0.000012,
  "profile_path": "/ofu7Z6xXpCpb4PJpOpbsH16cDR9.jpg"
}
```

I'm thinking of creating a custom date de-serializer which would attempt to convert a date, in this case, it would attempt to conver the year as `new DateTime(1970, 1, 1)`; if the conversion fails, the year would be `DateTime`'s default value. I'm hesitant about using nullable dates which would the the alternative if the conversion fails. Thoughts?

**Comment by hrafnl** [comment]
The Id passed to IApiPeopleRequest.FindByIdAsync(): 86232

Regarding the conversion proposed: No obvious correct way here.  If you use nullable dates, the client of the MovieDbWrapper at least knows that there is not date or the date could not be parsed.  Moreover, default values can be misleading: Are the default values or real values?

On the other hand, it is tedious to check for null!

**Comment by nCubed** [comment]
After reviewing with a few other developers, I've landed on converting the partial date. I believe this makes sense considering the data is crowd-sourced. Further, a Year is still better than a null date or DateTime.MinDate.

**Comment by nCubed** [comment]
Issue is closed; latest update has been published to Nuget and a new Release has been added where the compiled dll's can be downloaded directly from https://github.com/nCubed/TheMovieDbWrapper/releases/tag/v0.7.2
