### ISSUE TITLE
Runtime error in a Xamarin.UWP project

### ISSUE THREAD

**Issue by arividar** [nCubed/TheMovieDbWrapper#16]
Using TheMovieDbWrapper in a Xamarin Forms UWP project I get the following runtime exception:

    An exception of type 'System.PlatformNotSupportedException' occurred in mscorlib.ni.dll 
    but was not handled in user code
    Additional information: The value 'False' is not supported for property 'PreAuthenticate'.

I fixed it by removing line 145 from `ApiRequestBase.cs`:

    PreAuthenticate = false,

This should have no side-effects as PreAuthenticate defaults to false anyway. Could submit a pull-request with this.

**Comment by nCubed** [comment]
You're 100% correct that the `PreAuthenticate` property doesn't need to be set. I'ma bit surprised that it'd cause an issue, though. If you're finding that the removal of the property resolves the issue you're seeing with a Xamarin Forms UWP project, then a pull-request would be appreciated.

**Comment by arividar** [comment]
Fixed in pull request: #17
