### ISSUE TITLE
IMDB ID

### ISSUE THREAD

**Issue by ConsentDevelopment** [nCubed/TheMovieDbWrapper#19]
There does not seem a way to get the associated IMDB ID when using SearchByTitleAsync()?

**Comment by nCubed** [comment]
AFAIK, none of the basic search results from the Movie DB returns the associated IMDB Id. The only place I've seen the IMDB ID is on the full results returned with a Find by Id query.

In other words, search results typically return only a summary, whereas the full results can only be obtained once you have the Movie DB's Id retrieved from the search result.

This would require 2 queries:

1. `SearchByTitleAsync()` returns a `MovieInfo` class with an `Id` property of the Movie DB's Id.
2. `FindByIdAsync()` accepts a Movie DB Id and returns the full information, including the IMDB Id.

Does this work?

**Comment by ConsentDevelopment** [comment]
Your solution works perfectly.

Thanks for the fast response and solution 👍
