### ISSUE TITLE
Exception thrown when requesting certain TVShow details

### ISSUE THREAD

**Issue by LokiTata** [nCubed/TheMovieDbWrapper#23]
There is a problem when the info for requested TV show  `Task<ApiQueryResponse<TVShow>> FindByIdAsync(int tvShowId, string language = "en");` returns a null value for a season air_date because the property AirDate in the class Season is not supposed to be null. 
This is the case with a TV show called "Haven" with 33001 as TMDBId which has a record with a special season that has air_date: null
To replicate: 
`ApiQueryResponse<TVShow> responseInfo = await tvApi.FindByIdAsync(33001);`
Error: Cannot convert null value to System.DateTime. Path 'seasons[0].air_date', line 1, position 1006.

**Comment by nCubed** [comment]
Was wondering if the date field would be null in some instances. I'll take a look and see if a nullable DateTime makes sense or set as the default value of DateTime.

**Comment by LokiTata** [comment]
Great, thanks!

**Comment by LokiTata** [comment]
Any news on this?

**Comment by nCubed** [comment]
Resolved with Issue #25 and pull request #26. The issue was with the date converter which needed to handle a specific JSON serialization exception. Commit d23c334e4be21d6d56748d1f2269a8312964769d
