### ISSUE TITLE
[question] Episode Information Per Tv Show

### ISSUE THREAD

**Issue by GhostTheDreamWalker** [nCubed/TheMovieDbWrapper#31]
Just wanted to know if it is possible to pull episode information from the API per tv show?
Currently, you only get the episode count as far as I'm aware.

**Comment by nCubed** [comment]
TV shows will use the `IApiTVShowRequest`. There are examples in the integration test `ApiTVShowRequestTests`. See if those help, if not, describe in more detail what you are trying to do as well as your code.

**Comment by GhostTheDreamWalker** [comment]
Hi
You can close this issue. I found what I was looking for.
Thank you.
