### ISSUE TITLE
Adding Support for TV Episodes and Seasons

### ISSUE THREAD

**Issue by mejackhumphrey** [nCubed/TheMovieDbWrapper#36]
The Movie DB supports the following API details: 

- TV Episode Details: https://developers.themoviedb.org/3/tv-episodes/get-tv-episode-details
- TV Season Details: https://developers.themoviedb.org/3/tv-seasons/get-tv-season-details

As far as I can tell this is not supported in the IApiTVShowRequest interface?

**Comment by nCubed** [comment]
TV Episode/Season details have not been added. Looking at the API, getting them in should be fairly straight forward. The biggest time suck is creating the integration tests. But, I've been looking for a reason to update the wrapper, so let's get this rolling. Do you have anything else? Or are the details good enough?

**Comment by mejackhumphrey** [comment]
The details in those two endpoints are good enough. 
I would like this feature for a personal project I'm working on, if time is a factor for you I am happy to create a PR, would that be okay with you?

**Comment by nCubed** [comment]
A PR would be great. You'd need to follow the existing patterns; they should be clear after you look at a few implementations of the interfaces. And everything will need to have a full integration test backing the new end-points; again, check the current integration tests for the basic patterns. Let me know if that's something you're willing to take on, or if you're good waiting a week or so.

**Comment by mejackhumphrey** [comment]
That's something I'd be happy to take on. I haven't looked at the integration tests yet but the existing patterns in the rest of the project look easy enough to follow. 
I'll have a look at implementing this tomorrow afternoon (Europe time) and ping you if I have any questions.

**Comment by nCubed** [comment]
A quick review and the PR looks good on first glance. I'll review by tomorrow a.m. (US time). In the meantime, I'm going to add a couple of quick comments for some minor changes for consistency.
