### ISSUE TITLE
Should TV namespace be renamed to Television?

### ISSUE THREAD

**Issue by nCubed** [nCubed/TheMovieDbWrapper#5]
@yeah-buddy - what are your thoughts on updating the TV namespace to Television? Or, is TV more appropriate for the API?

**Comment by yeah-buddy** [comment]
TV is what is on the api calls and docs from TheMovieDb.org.  However, television would provide a "cleaner" namespace without the 2 capital letters right next to each other.  I'd imagine that's causing some R# noise.

**Comment by yeah-buddy** [comment]
I have no strong opinion either way.

**Comment by nCubed** [comment]
I've left the namespace as TV and added a R# team setting file to ignore TV inconsistent naming conventions.
